### ISSUE TITLE
Case issues on logs

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#286]
I made a plyer "Test1". When I use the "Virew logs" link on the generated startup page it gives an error about not finding log "test1". The welder/log folder contains a Test1.log not a "test1.log"

**Comment by kdemarest** [comment]
It depends on which log. Some buttons look at the Mesos log, while others
look at /welder/log/ThePlyerName.log

If not found, it could be because the log is on /tmp/mesos/slaves on a
different slave machine and we don't know how to read that yet.

*Ken Demarest*
*CEO, Appsoma *
ken@appsoma.com
415.342.9731
Austin, Texas ▪ United States

**Comment by zsimpson** [comment]
Fixed the issue for the top logs. The config is wrong for the actual mesos task logs. Wrote an email to Mark about thiat. Closing.
