### ISSUE TITLE
Upload screen also ~100px less tall... 

### ISSUE THREAD

**Issue by zsimpson** [appsoma/welder#4]
but in truth the "real" way to do this is probably to make the .welder-dataset-chooser change its height to match the screen's reality.

**Comment by zsimpson** [comment]
I also don't know what this means exactly.  The upload area is about 100px right now.  You want me to make it 0?

**Comment by kdemarest** [comment]
No. I meant to write "The Data Tab". The specific problem is, that after I drag a few files onto the Upload area, the green [Upload] button starts to scroll off the bottom of the screen.  I just realized I was having the problem because I dragged a lot of files over...

I think the [Upload] button needs to appear under the "or add files manually", or the user might miss it.  I also suggest the wording "Start Upload Now" on the button.  And the words "Drop files here should be explicit: "Drag and drop files here"

**Comment by zsimpson** [comment]
Changed the wording.
